repos:

# Flake8
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: [
          "wemake-python-styleguide",
        ]
        args: ["--config=.flake8"]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: double-quote-string-fixer
    -   id: debug-statements
        exclude: |
            (?x)^(
                .venv|
                venv|
                docs|
                img|
                notebooks|
                reports|
                .git|
            )$

# Imports order
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.2
    hooks:
    -   id: reorder-python-imports

# Trailing comma
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
    -   id: add-trailing-comma

# MyPy
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        exclude: |
            (?x)^(
                .venv|
                venv|
                docs|
                img|
                notebooks|
                reports|
                .git|
                test|
            )$
