repos:
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.257'
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: |
            (?x)^(
                .git/|
                .venv/|
                venv/|
            )$

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
        exclude: |
            (?x)^(
                .git/|
                .venv/|
                venv/|
            )$

# Imports order
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.2
    hooks:
    -   id: reorder-python-imports
        args: ["--application-directories=.:src"]

# Trailing comma
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
    -   id: add-trailing-comma
